### ISSUE TITLE
你好，能否增加无接种疫苗记录的显示？

### ISSUE THREAD

**Issue by yyked** [ilovexjp/ykm-simulator#1]
增加核酸48 ，72，小时的选择，增加疫苗记录接种可选时间，以及无接种疫苗记录的选择，以及无接种疫苗记录的绿码，再次感谢谢大佬，希望你能抽出时间更加完善一下粤康码

**Comment by ilovexjp** [comment]
这些功能有什么应用场景呢？

**Comment by yyked** [comment]
> 这些功能有什么应用场景呢？

无接种疫苗的人员需要出示证明，但是需要核酸

**Comment by yyked** [comment]
> 这些功能有什么应用场景呢？

企业，单位，公司之类的，按时上报，希望你能继续完善一下粤康码，这里无限感激

**Comment by ilovexjp** [comment]
这些需求感觉不太具有普遍性，且需要更改的页面交互比较多，暂时不会作为优先项。可能之后会视情况加入。

**Comment by Tianyulife** [comment]
希望增加疫苗接种记录页面，这样对某些强制接种疫苗的单位非常管用
