### ISSUE TITLE
我自己修改了下代码，修复了核酸界面和检测公司界面时间不统一问题和添加了右上角导航图案。希望作者看到采纳我这个代码文件用作修改

### ISSUE THREAD

**Issue by Ain-Jak** [ilovexjp/ykm-simulator#10]

**Comment by Ain-Jak** [comment]
[](url)[](url)
[ykm-simulator.zip](https://github.com/ilovexjp/ykm-simulator/files/9894040/ykm-simulator.zip)

**Comment by Ain-Jak** [comment]
随便也建议做个穗康码，在广州很多地方只认穗康码

**Comment by ilovexjp** [comment]
感谢你的贡献，但对于核酸检测的时间，健康码、场所通行、核酸检测记录三个界面显示的时间均不相同，感觉时间仍然是不统一的；另外你制作的右上角 UI 很棒！可否在其它项目上也使用你制作的这个样式？

**Comment by todesgottin** [comment]
大佬做的右上角ui太棒了  蹲一个更新！

**Comment by Ain-Jak** [comment]
> 你的另外一个人的时间，但同时又可能是三个不检测的人，健康，并记录了两个人的制作时间！在其他项目上也使用你制作的这个样式？

本质上没改变什么东西，只是优化了核酸时间和检测公司界面不会出现时间随机变化问题和右上角导航标志
![1243231](https://user-images.githubusercontent.com/116966822/198857178-93fee7a1-4c86-4c0a-9650-fa31649056c4.jpg)

**Comment by ilovexjp** [comment]
> > 你的另外一个人的时间，但同时又可能是三个不检测的人，健康，并记录了两个人的制作时间！在其他项目上也使用你制作的这个样式？
> 
> 本质上没改变什么东西，只是优化了核酸时间和核酸检测记录不会出现时间随机变化问题和添加了右上角导航标志，因为原来时间跳动变化太大不一致，只需要核酸时间和检测公司界面时间保持一致就行了，因为很多时候要出示报告，按照原来的之前变化太大很容易露馅 只是提个意见，把我这个基础上作为修改就可以了 ![1243231](https://user-images.githubusercontent.com/116966822/198857178-93fee7a1-4c86-4c0a-9650-fa31649056c4.jpg)

对于右上角的 UI，我按照你的想法对照着微信的实现（颜色、尺寸）修改了一下，稍后会更新；至于核酸检测的时间，我目前是想把这个功能再完善一下之后再更新，或许可以支持手动增删记录。

**Comment by Ain-Jak** [comment]
> > > 你的另外一个人的时间，同时还可能是三个人不检测的人，健康，但并记录了两个人的制作时间！在其他项目上也你制作了这个样式？
> > 
> > 
> > 基本原理并没有显示什么时间和显示检测结果，只是显示问题并没有显示出什么时间和显示检测结果，因为最初的时间变化和显示时间变化了，因为刚刚开始改变标志，需要时间和保持不变的公司形象，需要时间和保持不变基本一致的时候就很容易报告了，因为这个最初的变化很容易就暴露了![1243231](https://user-images.githubusercontent.com/116966822/198857178-93fee7a1-4c86-4c0a-9650-fa31649056c4.jpg)
> 
> 是的可以支持手动增删记录。



> > > 你的另外一个人的时间，但同时又可能是三个不检测的人，健康，并记录了两个人的制作时间！在其他项目上也使用你制作的这个样式？
> > 
> > 
> > 本质上没改变什么东西，只是优化了核酸时间和核酸检测记录不会出现时间随机变化问题和添加了右上角导航标志，因为原来时间跳动变化太大不一致，只需要核酸时间和检测公司界面时间保持一致就行了，因为很多时候要出示报告，按照原来的之前变化太大很容易露馅 只是提个意见，把我这个基础上作为修改就可以了 ![1243231](https://user-images.githubusercontent.com/116966822/198857178-93fee7a1-4c86-4c0a-9650-fa31649056c4.jpg)
> 
> 对于右上角的 UI，我按照你的想法对照着微信的实现（颜色、尺寸）修改了一下，稍后会更新；至于核酸检测的时间，我目前是想把这个功能再完善一下之后再更新，或许可以支持手动增删记录。

好的，无问题。期待你继续把功能做得更完善
