### ISSUE TITLE
希望可以添加红码、黄码页面

### ISSUE THREAD

**Issue by lydiagreenn** [ilovexjp/ykm-simulator#11]
红码、黄码有时候在某些方面可以用上，譬如请假。

**Comment by sienna911** [comment]
确实希望能增加这一功能，大大提高实用性，黄码红码对企业优先级很高，可解燃眉之急。希望能采纳，谢谢~

**Comment by ilovexjp** [comment]
本项目的初衷是反抗健康码——这个在集权下形式主义和官僚主义催生的反科学产物。本项目**永远不会**支持健康码的继续应用。
