### ISSUE TITLE
为什么我用ios系统，QQ浏览器解压后，里面很多图标都问号了？求解，多谢大佬

### ISSUE THREAD

**Issue by vean995** [ilovexjp/ykm-simulator#12]
为什么我用ios系统，QQ浏览器解压后，里面很多图标都问号了？求解，多谢大佬

**Comment by moebiusK** [comment]
用作者部署的网页吧，或者自己部署一个githubio，手机浏览器加载本地经常有点问题

**Comment by moebiusK** [comment]
> > 用作者部署的网页吧，或者自己部署一个githubio，手机浏览器加载本地经常有点问题
> 
> 請問可以幫我部署一個嗎？我IT白痴，但是很需要這個東西，尤其是看過富士康的事情後。

作者已经部署好了呀，Readme里面写了
Cloudflare: [ilovexjp.pages.dev/ykm](https://ilovexjp.pages.dev/ykm)
Netlify: [ilovexjp.netlify.app/ykm](https://ilovexjp.netlify.app/ykm)

**Comment by Chairman9527** [comment]
這兩個網頁已被防火牆屏蔽啦，沒有VPN上不去，家裡的老人家不懂用VPN，唉。> > > 用作者部署的网页吧，或者自己部署一个githubio，手机浏览器加载本地经常有点问题
> 
> > 
> 
> > 請問可以幫我部署一個嗎？我IT白痴，但是很需要這個東西，尤其是看過富士康的事情後。
> 
> 
> 
> 作者已经部署好了呀，Readme里面写了
> 
> Cloudflare: [ilovexjp.pages.dev/ykm](https://ilovexjp.pages.dev/ykm)
> 
> Netlify: [ilovexjp.netlify.app/ykm](https://ilovexjp.netlify.app/ykm)

**Comment by moebiusK** [comment]
> 這兩個網頁已被防火牆屏蔽啦，沒有VPN上不去，家裡的老人家不懂用VPN，唉。> > > 用作者部署的网页吧，或者自己部署一个githubio，手机浏览器加载本地经常有点问题
> 
> > > 
> > 
> > 
> > > 請問可以幫我部署一個嗎？我IT白痴，但是很需要這個東西，尤其是看過富士康的事情後。
> > 
> > 
> > 作者已经部署好了呀，Readme里面写了
> > Cloudflare: [ilovexjp.pages.dev/ykm](https://ilovexjp.pages.dev/ykm)
> > Netlify: [ilovexjp.netlify.app/ykm](https://ilovexjp.netlify.app/ykm)

这种网页大概率会被屏蔽的呀，没办法的事情。VPN教一下也不难吧，帮忙配置好节点，就是开关一下的问题。或者换一个手机浏览器试试，说不定直接就能本地加载。
