### ISSUE TITLE
ykm的时间能否做成自适应宽度

### ISSUE THREAD

**Issue by moebiusK** [ilovexjp/ykm-simulator#16]
我的手机上时间变成两行了，不知道是不是因为我的手机屏幕比较小（5.97寸），浏览器用的是via

![Screenshot_2022-11-03-19-51-45-565_mark via](https://user-images.githubusercontent.com/105786815/199714804-ee89880e-842c-4c92-adda-75af11c0a26a.jpg)

**Comment by ilovexjp** [comment]
本项目字体大小沿用原小程序的字体大小，仅将单位 rpx 转换为 vw，均为根据宽度自适应的单位，不会因屏幕宽度不同而出现换行问题。出现这个情况可能是字体问题或渲染错误导致。

**Comment by moebiusK** [comment]
> 本项目字体大小沿用原小程序的字体大小，仅将单位 rpx 转换为 vw，均为根据宽度自适应的单位，不会因屏幕宽度不同而出现换行问题。出现这个情况可能是字体问题或渲染错误导致。

好像确实和电脑上打开的字体不太一样，比电脑上要粗一点。我现在暂时是把时间字体大小手动从8vw调成7vw来用。

有办法统一解决这种情况吗？比如强制把时间限制成一行，如果不行就稍微缩小一点。我觉得实际使用的时候时钟稍微缩小一点问题不大，肉眼很难看出来，但是换行的话就直接暴露了。

**Comment by ilovexjp** [comment]
已经加入了强制不换行的约束，应该可以解决这个问题。

**Comment by moebiusK** [comment]
> 已经加入了强制不换行的约束，应该可以解决这个问题。

好的，谢谢

**Comment by moebiusK** [comment]
> 已经加入了强制不换行的约束，应该可以解决这个问题。

我这里还是换行的。。不知道为什么。您可以下个via浏览器测试一下吗？
