### ISSUE TITLE
请问可以制作只有核酸显示，无疫苗接种记录的粤康码吗？

### ISSUE THREAD

**Issue by yyked** [ilovexjp/ykm-simulator#2]
当然中间的绿码也要修改的，大概像通行码那样没有雄狮，最好通行码也来一个有核酸无疫苗接种的版本，以上。

最后是感谢你的付出劳动，本人除了感谢似乎帮不上你的什么忙，【笑】希望你能抽出宝贵的时间实现一下我的心愿啦！

**Comment by ilovexjp** [comment]
#1 相同的内容请不要多开 Issues，谢谢
