### ISSUE TITLE
On Safari PWA, Status Bar is not Hidden

### ISSUE THREAD

**Issue by mata8** [ilovexjp/ykm-simulator#20]
Currently on Safari 15, the notch area for PWA is not covered by the web page, here's the screenshot:

![IMG_1211](https://user-images.githubusercontent.com/9066113/200155980-230637bd-3e1d-47d9-acca-ddedbbaec247.jpg)

It seems that in `<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">`, the value `black-translucent` is not working

Also, I've added the tag `<meta name="apple-mobile-web-app-capable" content="yes">`, but still no luck

System version: 15.0

**Comment by ilovexjp** [comment]
I'm aware of this issue and currently there's no optimal solution to this. A workaround is to install the PWA on the catalog page rather than on the health code page, in this way the color of the status bar should be showing correctly.

**Comment by mata8** [comment]
Okay, I've done some digging. 

The `black-translucent` value seems deprecated according to this [article](https://firt.dev/ios-14.5/#status-bar-change)

The `default` or `hidden` values can make the status bar visible but still not translucent like the original one.

`default` or `hidden`:
![IMG_1212](https://user-images.githubusercontent.com/9066113/200161571-adf4e660-9704-45b7-a5dc-22c383248f33.jpg)

Original:
![IMG_1213](https://user-images.githubusercontent.com/9066113/200161565-342d8bcd-5e8a-4d9d-84e1-e675c63549cd.jpg)

So I've added the `viewport-fit=cover` in `viewport` field:
`<meta name="viewport" content="initial-scale=1,user-scalable=no,viewport-fit=cover">`

It became like this:
![IMG_1214](https://user-images.githubusercontent.com/9066113/200161712-924a9a19-133a-431f-9074-d28a541ea1de.jpg)

Then we can propbably mimicking the interface by pushing down the whole body a little bit.

Anyway, much appreciate for the hard work.
