### ISSUE TITLE
一人血书求「核酸检测记录页」

### ISSUE THREAD

**Issue by bqliang** [ilovexjp/ykm-simulator#4]
丧心病狂要提交核酸检测记录截图…非常苦闷  

===========

![Screenshot_2022-10-24-11-34-21-242_com tencent mm-edit](https://user-images.githubusercontent.com/61445006/197443662-eb898a02-1598-42a0-a1f1-092fdfcdb022.jpg)

**Comment by yyked** [comment]
支持！

**Comment by ilovexjp** [comment]
已添加核酸检测记录页面。
