### ISSUE TITLE
能否支持沉浸式状态栏

### ISSUE THREAD

**Issue by zippno** [ilovexjp/ykm-simulator#5]
试了安卓chrome打开demo页面，顶部状态栏还是系统状态栏自带样式， 希望能支持沉浸式状态栏，就像B站一样，样式更好看，效果也会更真实，十分感谢
![图片](https://user-images.githubusercontent.com/11855728/197549158-73f04100-b993-467e-9ae9-e2c07bca634d.png)

**Comment by ilovexjp** [comment]
已更新，可前往 [健康码模拟索引](https://github.com/ilovexjp/health-code-index) 下载源码及预览。

**Comment by 1847128171** [comment]
![IMG_20221026_155439](https://user-images.githubusercontent.com/61436055/197967696-3be2b25d-36c7-44b2-8d45-dfb3b82d6527.jpg)
能不能把这个也舔加上去，这样更真实，我们没办法布暑到小程序

**Comment by 1847128171** [comment]
@ilovexjp 可以把微信小程序那个回收键，跟菜单栏添加上去吗，这样真的很真实

**Comment by ilovexjp** [comment]
> @ilovexjp 可以把微信小程序那个回收键，跟菜单栏添加上去吗，这样真的很真实

不同的建议请另开 Issue。
