### ISSUE TITLE
謝謝大神的傑作，然螞蟻們還有生存空間，但是自從今天你的粵康碼程序更新以後，我無法打開網頁，怎麼辦？心急如焚吖！ 求不連網的版本啊！

### ISSUE THREAD

**Issue by Chairman9527** [ilovexjp/ykm-simulator#8]

**Comment by ilovexjp** [comment]
原因应该是中国大陆运营商对这两个网站（Cloudflare、Netlify）的屏蔽，可以尝试使用代理访问，或自行部署源码。

**Comment by Chairman9527** [comment]
> 原因应该是中国大陆运营商对这两个网站（Cloudflare、Netlify）的屏蔽，可以尝试使用代理访问，或自行部署源码。

是的，所以求大神做一個離線安卓版！謝謝。

**Comment by unclefive55** [comment]
顺便请问release里面的源码怎么部署呢...........
