### ISSUE TITLE
感谢大佬！顺便问下有无广东的前端小伙伴帮忙分享一下穗康和场所这两个码的

### ISSUE THREAD

**Issue by senup** [ilovexjp/ykm-simulator#9]

**Comment by JimmyBoot** [comment]
对呀，今天观察了下，附近很多场所竟然只提供穗康的场所码

**Comment by yyked** [comment]
还有这种码？

**Comment by todesgottin** [comment]
是啊 广州有两个码。大多数地方只提供穗康码，有这个很多地方也不给进。他门口一定要你扫穗康码才能进，现在到处都要48小时核酸。真得不想做又必须要上班。血求作者做一个穗康码

**Comment by JimmyBoot** [comment]
所以最近一直都是用视频录屏进出各大场所（天河中心、写字楼、商场），做了核酸就把健康码和平时用的频繁的场所码录起来保存。用形式主义对抗形式主义！！
ps 你不要把码子怼到保安脸上给人看，据不负责任观察并亲测：他们只是看颜色确定你是绿+紫就OK了

**Comment by todesgottin** [comment]
主要是有些防疫爱好者一定要你扫穗康码 还不认粤康码，必须要扫扫了必须要看。现在全都要48小时就不想做核酸啊

**Comment by kanno6** [comment]
急需穗康码和穗康码场所码

**Comment by senup** [comment]
主要是前端有点陌生，不然反编译的话应该是可以拿到前端页面源码的

**Comment by moebiusK** [comment]
穗康码那里现实的就是“粤康码（广州）”，然而UI不太一样

**Comment by acoffeeworld** [comment]
同求

**Comment by llkhs** [comment]
同求，还有健康申报卡的页面，关键时刻非常有作用！
